sudo: false

language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7
  - 6

cache:
  directories:
  - node_modules

before_install:
  - npm i -g npm@lts

install:
- npm install

script:
  - npm run test
  - npm run build