sudo: required

services:
  - docker

language: node_js

node_js:
  - 10

cache:
  directories:
  - node_modules

before_install:
  - npm i -g npm@lts

install:
  - npm install

script:
  - npm run test

after_success:
  - sh ./deploy_dockerhub.sh
